image: registry.git.chalmers.se/courses/dit638/students/docker/docker:19.03.3

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_CLI_EXPERIMENTAL: enabled
  CI_REGISTRY_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH
  BUILDX_VERSION: 0.7.1
  CI_BUILDX_ARCHS: "linux/amd64,linux/arm64,linux/arm/v7"

services:
  - name: registry.git.chalmers.se/courses/dit638/students/docker/docker:19.03.3-dind
    alias: docker 
stages:
  - build
  - deploy

# Display information before we start the build.
before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker run --rm --privileged registry.git.chalmers.se/courses/dit638/students/2024-group-08/qemu-user-static --reset -p yes
  - docker buildx create --name groupbuilder --use
  - docker buildx inspect --bootstrap

# This section describes what shall be done to build and test the project.
build-and-test:
  only:
    - branches
  tags:
    - docker-build
  stage: build
  script:
    - echo "Building with Buildx..."
    - docker buildx build --platform $CI_BUILDX_ARCHS -f Dockerfile -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" --push .

# This section describes what shall be done to deploy artefacts from the project.
release:
  script:
    - echo "Deploying to Registry...."
    - docker buildx build --platform $CI_BUILDX_ARCHS -f Dockerfile -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" --push .
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
  tags:
    - docker-build
  stage: deploy
