image: registry.git.chalmers.se/courses/dit638/students/docker/docker:19.03.3

variables:
  DOCKER_HOST: tcp://docker:2375
  CI_BUILDX_ARCHS: "linux/amd64,linux/arm64,linux/arm/v7"
  BUILDX_URL: https://github.com/docker/buildx/releases/download/v0.7.1/buildx-v0.7.1.linux-amd64

services:
  - name: registry.git.chalmers.se/courses/dit638/students/docker/docker:19.03.3-dind
    alias: docker
stages:
  - build
  - deploy

# Display information before we start the build.
before_script:
  - docker image prune -f
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# This section describes what shall be done to build and test the project.
build-and-test:
  only:
    - branches
  tags:
    - docker-build
  stage:
    build
  script:
    - docker build -t name:latest -f Dockerfile .

# This section describes what shall be done to deploy artefacts from the project.
release:
  script:
    - export DOCKER_CLI_EXPERIMENTAL=enabled
    - mkdir -p ~/.docker/cli-plugins
    - wget -O ~/.docker/cli-plugins/docker-buildx $BUILDX_URL
    - chmod 755 ~/.docker/cli-plugins/docker-buildx
    - docker info
    - docker version
    - docker buildx create --name platformbuilder --use
    - docker buildx build --push $CI_BUILDX_ARCHS -t "$CI_REGISTRY-IMAGE":"$CI_COMMIT_TAG" .
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
  tags:
    - docker-build
  stage: deploy
