image: registry.git.chalmers.se/courses/dit638/students/docker/docker:19.03.3

#Detalis about how to connect to the docker service to run this build
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - name : registry.git.chalmers.se/courses/dit638/students/docker/docker:19.03.3-dind
    alias: docker
stages:
  - build
  - deploy

# Display information before we start the build.

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# This section describes what shall be done to build and test the project.
build-and-test:
  tags:
    - docker-build
  stage: build
  script: 
    - docker build -f /builds/courses/dit638/students/2024-group-08/Dockerfile .

# This section describes what shall be done to deploy artefacts from the project.
release:
  tags:
    - docker-build
  stage: deploy
  script:
    - docker build -f Dockerfile -t "$CI_REGISTRY_IMAGE":"$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY_IMAGE":"$CI_COMMIT_TAG"

  rules:
    - if: $CI_COMMIT_TAG =~ /^v(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)$/
      when: always
